# 设定全局变量global_result
global_result = ""

# 设定全局变量Global_Bearer
Global_Bearer = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBVc2VySWQiOiJvck94VzRfZU85TlVVVnlVbWg2eXVGNXlZbGdvIiwiZXhwIjoxNzIzODIzMDUyLCJpYXQiOjE3MTU3ODc4NTIsImlkIjoxNjE3NDk5NywibmFtZSI6IjE3Njg4MDgxODM0In0.D3ztT_tYc-TYFzNMoCM_Ii3vYJ1qLsfryRGgwg34QiY"