# 设定全局变量global_result
global_result = ""

# 设定全局变量Global_Bearer
Global_Bearer = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBVc2VySWQiOjExMzI4ODM3LCJleHAiOjE3MTAzNDE3NTAsImlhdCI6MTcwMjMwNjU1MCwiaWQiOjE2MTc0OTk3LCJuYW1lIjoiMTc2ODgwODE4MzQifQ.MI9tZUn6ki8EfiZHgUXCE7VYe6JN6UJLcPz6YgbtaYA"